# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

AllCops:
  Exclude:
    - test/dummy/db/schema.rb
    - test/dummy/db/queue_schema.rb
    - test/dummy/db/migrate/**/*
